// <auto-generated />
namespace P3_Segunda_Parte.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _26NovPedidos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26NovPedidos));
        
        string IMigrationMetadata.Id
        {
            get { return "201811270117567_26Nov-Pedidos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
