// <auto-generated />
namespace P3_Segunda_Parte.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _30nov : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30nov));
        
        string IMigrationMetadata.Id
        {
            get { return "201811302003190_30nov"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
